import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import Container from "../components/container"
import "./globals.css"

const openSans = Open_Sans({
	variable: "--font-open-sans",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Книгарня 'Еники-Беники'",
	description: "Generated by Eniki Beniki team",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${openSans.variable} antialiased`}>
				<Container>{children}</Container>
			</body>
		</html>
	)
}
