// src/app/layout.tsx
import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import "swiper/css"
import "swiper/css/navigation"
import "swiper/css/pagination"
import "../styles/swiper-styles.css"
import AppProvider from "./appProvider"
import "./globals.css"

const openSans = Open_Sans({
	variable: "--font-open-sans",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Книгарня 'Еники-Беники'",
	description: "Generated by Eniki Beniki team",
}

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="uk">
			<body className={`${openSans.variable} antialiased bg-customWhite`}>
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	)
}
