import { GoogleOAuthProvider } from "@react-oauth/google"
import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import AppProvider from "./appProvider"
import "./globals.css"

const openSans = Open_Sans({
	variable: "--font-open-sans",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Книгарня 'Еники-Беники'",
	description: "Generated by Eniki Beniki team",
}

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="uk">
			<body className={`${openSans.variable} antialiased bg-customWhite`}>
				<GoogleOAuthProvider
					clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
				>
					<AppProvider>{children}</AppProvider>
				</GoogleOAuthProvider>
			</body>
		</html>
	)
}
